### PR TITLE
Preserve the SSH_AUTH_SOCK environment variable

### LINKED ISSUE #367: SSH agent configuration isn't preserved
# Problem/Motivation

Similar to a previous issue (#271), I wanted to push my config back up to GitHub from within the SSH addon environment, using my SSH key held in the agent on my laptop.
Despite enabling agent forwarding in the addon config and connecting with `ssh- A`, git pushing fails. Interacting with SSH agent (`ssh-add -l`) shows the system cannot connect to my (forwarded) agent.

## Expected behavior

When connecting with the `-A` parameter, the SSH agent connection should work, `ssh-add -l` should list keys loaded in the remote agent.

## Actual behavior

`ssh-add` reports it "Could not open a connection to your authentication agent."

## Steps to reproduce

1. Enable `allow_agent_forwarding` in the addon configuration options (ensure` ssh:username` is **not** set to `root`)
2. Add authorized keys in config options
3. Map the container port to a host port (e.g. 22) in the add network configuration
4. Restart the addon
5. Connect to the addon environment with `ssh -A hassio@<haos host/ip address> -p <port>`
6. Attempt to list keys loaded in the agent:

    ```shell
    $ ssh-add -l
    Could not open a connection to your authentication agent.
    ```

7. Observe that the forwarded SSH agent socket does not exist:

    ```shell
    $ env | grep SSH_
    $
    ```

## Proposed changes

The issue arises because the default user (`hassio`) is configured to immediately switch to root in `~/.profile`:

```shell
exec sudo -i
```

This does not preserve the shell environment from the `hassio` user, notably the `SSH_AUTH_SOCK` environment variable, which is needed to connect to the (forwarded) SSH agent.
A workaround is to edit `/home/hassio/.profile` to preserve that variable:

```shell
exec sudo --preserve-env=SSH_AUTH_SOCK -i
```

The variable is then present, and the agent works as expected:

```shell
$ echo $SSH_AUTH_SOCK
/tmp/ssh-XXXXhpjhmn/agent.1631
$ ssh-add -l
4096 ssh-rsa SHA256:XXXXXXXX... id_rsa (RSA)
```

The environment variable preservation could also be set in the `/etc/sudoers` configuration by using the `env_keep+=` directive.

### PR DESCRIPTION
**Pull request by imgrant**
# Proposed Changes

Add `--preserve-env=SSH_AUTH_SOCK` to the `sudo` invocation that switches to `root` immediately upon login (from, e.g. `hassio` user)

N.b. it's fine to leave this in by default, since if `allow_agent_forwarding` is false, the agent won't work.

## Related Issues

fixes #367 SSH agent configuration isn't preserved

### CODE REVIEW

**Comment by imgrant** [comment]
This PR is really simple, I wonder if someone could review it? The linked issue, #367, is also languishing as unloved. ☹️

File: ssh/rootfs/etc/cont-init.d/ssh.sh [hunk 1]
```diff
@@ -106,7 +106,7 @@ if [[ "${username}" != "root" ]]; then
         || bashio::exit.nok 'Failed adding user to wheel group'
 
     # Ensure new user switches to root after login
-    echo 'exec sudo -i' > "/home/${username}/.profile" \
+    echo 'exec sudo -i --preserve-env=SSH_AUTH_SOCK' > "/home/${username}/.profile" \
```
Comment (frenck) [inline ssh/rootfs/etc/cont-init.d/ssh.sh:109]: Let's not solve this here, but in the sudoers configuration instead.

**Review by frenck — CHANGES_REQUESTED** [review]

File: ssh/rootfs/etc/cont-init.d/ssh.sh (hunk 1 above)
Comment (imgrant) [reply ssh/rootfs/etc/cont-init.d/ssh.sh]: Sure, done, updated commit pushed

**Review by frenck — APPROVED** [review]
Thanks, @imgrant 👍
